Migrates to null safety
flutter/flutter_image pull request #22
Opened 2021-03-22 12:57 UTC by Ascenio

- Updates dependencies
- Changes SDK constraints
- Makes required changes to move to null safety
- Bumps version

2021-03-27 09:41 UTC, arsamme approved these changes

2021-03-29 09:14 UTC, arsamme commented
@Ascenio Thanks for your PR but if fails in some tests, Would you please check?

2021-03-29 10:22 UTC, NoamDev commented
@arsamme actually those test failures happen even with the current master.
See https://github.com/flutter/flutter_image/pull/23 for example, I only changed analysis options and it fails in exactly the same way.

2021-03-29 12:35 UTC, NoamDev commented
@iapicca see this too.

> 
> 
> @arsamme actually those test failures happen even with the current master.
> See #23 for example, I only changed analysis options and it fails in exactly the same way.

2021-03-29 14:08 UTC, Ascenio commented
Ok so I changed it such that when the download of the image fails it throws an error instead of returning null (as it was before). This is required because `OneFrameImageStreamCompleter` expectes a `Future<ImageInfo>` instead of `Future<ImageInfo?>`. So after that I've made some changes to tests and reorganized them. So far seems to work. @mit-mit could you, please, take a look?

2021-03-30 09:12 UTC, arsamme commented
@mit-mit Hi, Could you please check this PR and merge?

2021-03-30 09:42 UTC, iapicca commented
> @iapicca see this too.

@NoamDev
I'm no expert, but since I'm [asked](https://github.com/flutter/flutter_image/pull/22#issuecomment-809341502)

```dart
if (instructions.alternativeImage != null)
      return instructions.alternativeImage;

    assert(lastFailure != null); //// <= is usin != null assertion still the right way to do it?

-    FlutterError.onError(FlutterErrorDetails(
-      exception: lastFailure,
+    FlutterError.onError!(FlutterErrorDetails(
+      exception: lastFailure!,
      library: 'package:flutter_image',
      context: ErrorDescription('$runtimeType failed to load ${instructions.uri}'),
    ));

-    return null;
+   throw lastFailure;    /// <= isn't this a significant change in behavior?
  }
```

2021-03-30 12:48 UTC, Ascenio commented
Exacly. Before it was returning null once it failed to load a image, but as right now, with null safety, it expects always a non-null value, so I think the only workaround is to throw a exception such that it returns a `Future.error`. Because we can not simply return null. I don't really know how `OneFrameImageStreamCompleter` works, but, assuming from its API, this is the only expected behavior I can think of.

2021-03-30 12:49 UTC, Ascenio commented
But from the user's point of view things it shouldn't be a breaking change. It _should_ fail in the same cases it did before.

2021-03-30 12:59 UTC, mit-mit commented
@kf6gpe could you find someone to review (and publish if taken) this PR?

2021-03-30 16:16 UTC, kf6gpe commented
@stuartmorgan who's been on top of plugins & ecosystems.

2021-04-03 03:02 UTC, arsamme commented
@stuartmorgan Hi there, Any updates on this?

2021-04-05 16:52 UTC, stuartmorgan requested changes
It doesn't look like this package has a current owner, so I can review (with the caveat that I'm not familiar with this code).

2021-04-05 16:52 UTC, stuartmorgan commented on lib/network.dart
> +            .timeout(instructions.timeout!);
If `timeout` can't be null in the places it's needed, then `FetchInstructions` should be reworked to make the timeout non-nullable. The case where it's not used can have a dummy value instead of null.

2021-04-05 16:52 UTC, stuartmorgan commented on lib/network.dart
> +          );
Why have you changed the API to throw when the fetch succeeds and gets zero bytes?

2021-04-05 16:52 UTC, stuartmorgan commented on lib/network.dart
> +    FlutterError.onError!(FlutterErrorDetails(
The docs specifically say this can be set to null to ignore errors; this is not safe.

2021-04-05 16:52 UTC, stuartmorgan commented on lib/network.dart
> +    throw lastFailure;
Why this API change?

2021-04-05 16:52 UTC, stuartmorgan commented on lib/network.dart
> +  static bool defaultTransientHttpStatusCodePredicate(int? statusCode) {
Making this nullable will cause a null value to silently return false, which is almost certainly not going to be what the calling code intended. This should be non-nullable, and the caller should be handling null.

2021-04-05 16:52 UTC, stuartmorgan commented on pubspec.yaml
> +version: 4.0.0
This needs a corresponding CHANGELOG change.

2021-04-05 17:39 UTC, Ascenio commented on lib/network.dart
> +          );
Because the previous behavior of downloading a "empty image" is the same as getting no response at all.

2021-04-05 17:40 UTC, iapicca commented on lib/network.dart
> +    throw lastFailure;
that's what I meant https://github.com/flutter/flutter_image/pull/22#issuecomment-810077503

2021-04-05 17:43 UTC, Ascenio commented on lib/network.dart
> +    FlutterError.onError!(FlutterErrorDetails(
Sure, I can not disagree. However as tried my best to kept the same behaviour, looks like before there weren't any checks for null either, which made me think that at this point of the code there's _implicitly_ a onError defined.

2021-04-05 17:45 UTC, stuartmorgan commented on lib/network.dart
> +    FlutterError.onError!(FlutterErrorDetails(
This code has no way of guaranteeing that; it was simply not correct before in that edge case. Migration to null-safety should fix issues that are exposed by the migration, not explicitly codify that.

2021-04-05 17:45 UTC, Ascenio commented on lib/network.dart
> +    FlutterError.onError!(FlutterErrorDetails(
Would change it for `FlutterError.onError?` be enough?

2021-04-05 17:46 UTC, Ascenio commented on lib/network.dart
> +            .timeout(instructions.timeout!);
Sure. I made it so that default timeout is `Duration.zero`.

2021-04-05 17:59 UTC, Ascenio commented on lib/network.dart
> +    throw lastFailure;
Ok so this is the main point, you can see some discussions above. The method above is `_loadWithRetry()`
Basically, the return of this function _has_ to be non-nullable because it's used with OneFrameImageStreamCompleter.
https://github.com/flutter/flutter_image/blob/cc77a20a4f6781e66ea2a352460b844840b06b21/lib/network.dart#L76-L82
The signature of the constructor is
```dart
OneFrameImageStreamCompleter(
  Future<ImageInfo> image, {
  Iterable<DiagnosticsNode> Function()? informationCollector
})
```
which means we can not return null, instead we should throw some error.

2021-04-05 18:21 UTC, Ascenio commented on lib/network.dart
> +  static bool defaultTransientHttpStatusCodePredicate(int? statusCode) {
Sure.

2021-04-05 18:29 UTC, Ascenio commented on pubspec.yaml
> +version: 4.0.0
Oh, my bad. I didn't noticed the repo had a CHANGELOG.

2021-04-05 18:35 UTC, Ascenio commented on lib/network.dart
> +          );
And because we can not return null, this is, to me, the only option left.

2021-04-06 14:22 UTC, stuartmorgan commented on lib/network.dart
> +    FlutterError.onError!(FlutterErrorDetails(
Yes, if it's null'd then doing nothing for this line seems correct.

2021-04-06 14:39 UTC, stuartmorgan requested changes
Sorry, I had missed some of the discussion above. Given the restrictions, the throws here seem reasonable (again with the caveat that I'm not familiar with the API, so am not an ideal reviewer for actual API changes).

2021-04-06 14:39 UTC, stuartmorgan commented on CHANGELOG.md
> +* **Breaking change**. Updates for Flutter 2.0.0
Updating for Flutter 2 isn't a breaking change, so I'm not sure why you've grouped these. Only the null safety migration is breaking.

2021-04-06 14:39 UTC, stuartmorgan commented on CHANGELOG.md
> +- Introduces null safety
Please describe the changes to error flow that you made here as they affect clients.

2021-04-06 14:39 UTC, stuartmorgan commented on lib/network.dart
> +      exception: lastFailure!,
It's not clear to me that it's impossible to create a fetch strategy such that there are no tries, in which case this isn't safe; there should be a fallback here instead of `!`.

2021-04-06 15:30 UTC, Ascenio commented on CHANGELOG.md
> +* **Breaking change**. Updates for Flutter 2.0.0
Actually I've only put as breaking change because previous changelogs messages were just like this. As upgrading to Flutter 2.0 is a breaking change in most cases, this is why it's recommended to update the major version, and this was what I did. But, to be fair, there shouldn't be significant changes from the client's point of view.

2021-04-08 07:57 UTC, kengu commented
@mit-mit Do you have time to review this PR? It is blocking other packages from migrating to sound null-safety.

2021-04-08 08:10 UTC, mit-mit commented
Stuart already reviewed it above; looks like we're still waiting for more updates per that review.

2021-04-08 13:18 UTC, Ascenio commented on lib/network.dart
> +      exception: lastFailure!,
Weird, seems like the `FlutterError.onError?(...)` is not a valid syntax. Anyway, I added a simple if check to make it safer

2021-04-08 16:07 UTC, Ascenio commented on CHANGELOG.md
> +- Introduces null safety
Actually there's not a breaking change because the behavior is the same and I've tested agaisnt flutter's own `Image.network` and when image loading fails [it throws a exception too](https://github.com/flutter/flutter/blob/98a96189937105f51e58e65543e2c6019a82cb33/packages/flutter/lib/src/painting/_network_image_io.dart#L123). So I think we are good to go.

2021-04-08 16:08 UTC, Ascenio commented on CHANGELOG.md
> +- Introduces null safety
I've noticed that `Image.network` doesn't logs through Flutter.onError because when there is a exception the user knows already. So maybe we should remove it too.

2021-04-08 16:19 UTC, Ascenio commented on CHANGELOG.md
> +- Introduces null safety
Also when the image has zero bytes, [it throws too](https://github.com/flutter/flutter/blob/98a96189937105f51e58e65543e2c6019a82cb33/packages/flutter/lib/src/painting/_network_image_io.dart#L112-L113)

2021-04-08 20:50 UTC, stuartmorgan commented on CHANGELOG.md
> +- Introduces null safety
> Actually there's not a breaking change because the behavior is the same

I'm confused; didn't you change the behavior of how `load`—which is public API of this package—resolves the completer that it returns?

2021-04-08 20:55 UTC, Ascenio commented on CHANGELOG.md
> +- Introduces null safety
Yes. But the changes doesn't affect the client because he doesnt use load directly. All the client can see is:
```dart
Image(
  image: NetworkImageWithRetry('http://example.com/avatars/123.jpg'),
);
```
which didn't changed.

2021-04-08 21:16 UTC, stuartmorgan commented on CHANGELOG.md
> +- Introduces null safety
Again, it's public API. How do you know which public APIs of this package all clients are using?

2021-04-08 21:42 UTC, Ascenio commented on CHANGELOG.md
> +- Introduces null safety
Right, that makes sense. I will take another look and take some notes about what I think changed and it's important.

2021-04-10 09:50 UTC, Lootwig commented on CHANGELOG.md
> +- Introduces null safety
I've had a look at the implementation of the returned class (`OneFrameImageStreamCompleter`):
What's changed is that before, returning `null` from `_loadWithRetry()` would have resulted in an exception caught within `setImage()` while notifying listeners, without calling the optional `InformationCollector` supplied to the constructor.

The null-safe implementation causes the `null` case to be handled by the `onError` handler assigned to the `image` Future, which _does_ report the error using the `InformationCollector`, and also makes the error "silent", i.e. it will be ignored by the default error handler in release mode as per [the FlutterErrorDetails doc](https://api.flutter.dev/flutter/foundation/FlutterErrorDetails/silent.html).


Feel free to use any part of this for the changelog, I understand a description of the behavior in there is all that was asked for by @stuartmorgan

2021-04-27 14:52 UTC, stuartmorgan commented
@Ascenio Are you still planning on updating this PR to describe the API changes?

2021-04-30 02:50 UTC, Ascenio commented
Sure. I'll have a look at it this weekend.

2021-05-02 19:00 UTC, aytunch commented
Hi all,
What is the hold here? As far I see, the PR looks solid.

2021-05-03 10:24 UTC, ThexXTURBOXx commented
@Ascenio You could also use the `RetryClient` from `http 0.13.2` in order to have it to retry failed requests automatically. This would *maybe* be a nice cleanup

2021-05-03 11:20 UTC, tlueder commented
@Ascenio @ThexXTURBOXx let’s do that in a follow-up PR please.

2021-05-03 14:30 UTC, stuartmorgan commented
> Hi all,
> What is the hold here? As far I see, the PR looks solid.

Please read the comments directly above yours, which describe what it is waiting on.

2021-05-03 18:58 UTC, Ascenio commented
Sorry by the delay, let me know if there's anything I've missed.

2021-05-03 19:01 UTC, Ascenio commented
@ThexXTURBOXx that's nice, should reduce the most important method's size significantly. As of now it might better to not delay this PR and leave this idea to a following one as @tlueder suggests.

2021-05-03 19:04 UTC, ThexXTURBOXx commented
@Ascenio Yes, let's do that in the near future. I tried doing it, but we would need to include `http` as an additional dependency, hence increasing dependency pollution (right now it is very lightweight, nearly only needing internal libraries)

2021-05-06 06:13 UTC, Marthijs-Berfelo commented
@stuartmorgan Could you indicate when you have time to review the latest changes by @Ascenio?

2021-05-12 15:12 UTC, stuartmorgan approved these changes
Thanks, I pared down the CHANGELOG to just the specific breaking change it discussed; there's no need to cover existing behavior in a CHANGELOG, or to discuss implementation details. Also, we don't generally discuss the specific nullability changes in the API surface since nullability changes are an implied part of a null safety migration.

LGTM with that change.

2021-05-12 15:15 UTC, merged